/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { MyName as MyName } from './components/my-name/my-name';

interface HTMLMyNameElement extends MyName, HTMLElement {
}
declare var HTMLMyNameElement: {
  prototype: HTMLMyNameElement;
  new (): HTMLMyNameElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-name": HTMLMyNameElement;
  }
  interface ElementTagNameMap {
      "my-name": HTMLMyNameElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-name": JSXElements.MyNameAttributes;
      }
  }
  namespace JSXElements {
      export interface MyNameAttributes extends HTMLAttributes {
        
          first?: string,
          last?: string
      }
  }
}

import { WuCol as WuCol } from './components/wu-col/wu-col';

interface HTMLWuColElement extends WuCol, HTMLElement {
}
declare var HTMLWuColElement: {
  prototype: HTMLWuColElement;
  new (): HTMLWuColElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "wu-col": HTMLWuColElement;
  }
  interface ElementTagNameMap {
      "wu-col": HTMLWuColElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "wu-col": JSXElements.WuColAttributes;
      }
  }
  namespace JSXElements {
      export interface WuColAttributes extends HTMLAttributes {
        
          basis?: string
      }
  }
}

import { WuRow as WuRow } from './components/wu-row/wu-row';

interface HTMLWuRowElement extends WuRow, HTMLElement {
}
declare var HTMLWuRowElement: {
  prototype: HTMLWuRowElement;
  new (): HTMLWuRowElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "wu-row": HTMLWuRowElement;
  }
  interface ElementTagNameMap {
      "wu-row": HTMLWuRowElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "wu-row": JSXElements.WuRowAttributes;
      }
  }
  namespace JSXElements {
      export interface WuRowAttributes extends HTMLAttributes {
        
      }
  }
}

